name: Staging Test Suite

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        
    - name: Install monorepo dependencies
      run: yarn holoInstall
      
    - name: Run BE tests
      run: yarn test
        
    - name: Run FE tests
      working-directory: ./frontend
      run: yarn test
    
    - name: Build Test
      run: yarn build
